[features]
seeds = false
[programs.localnet]
escrow_anchor = "4NpAm9u4XrXYdKK7Lma7AA3UVSDzDntmQxmeDen8mBx5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/ricardocastelloroman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
